/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadoracontador.apresentacao;

import javax.swing.JButton;
import calculadoracontador.negocios.Calculadora;
import calculadoracontador.negocios.excecoes.OperadorNaoEncontradoException;
import calculadoracontador.negocios.excecoes.Operando1NaoDefinidoException;
import calculadoracontador.persistencia.Operacao;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Pedro
 */
public class CalculadoraUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraUI
     */
    public CalculadoraUI() {
        initComponents();
        // cria uma nova calculadora para realizar as operações
        this.calc = new Calculadora();
        this.setTitle(NOME_DO_PROGRAMA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextResultado = new javax.swing.JTextField();
        jBntClear = new javax.swing.JButton();
        jBtnNumero7 = new javax.swing.JButton();
        jBtnNumero8 = new javax.swing.JButton();
        jBtnNumero9 = new javax.swing.JButton();
        jBtnOperacaoDiv = new javax.swing.JButton();
        jBtnNumero4 = new javax.swing.JButton();
        jBtnNumero5 = new javax.swing.JButton();
        jBtnNumero6 = new javax.swing.JButton();
        jBtnOperacaoMul = new javax.swing.JButton();
        jBtnNumero1 = new javax.swing.JButton();
        jBtnNumero2 = new javax.swing.JButton();
        jBtnNumero3 = new javax.swing.JButton();
        jBtnOperacaoSub = new javax.swing.JButton();
        jBtnNumero0 = new javax.swing.JButton();
        jBtnPonto = new javax.swing.JButton();
        jBtnOperacaoIgual = new javax.swing.JButton();
        jBtnOperacaoAdi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextLog = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextResultado.setEditable(false);
        jTextResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextResultado.setFocusable(false);

        jBntClear.setText("C");
        jBntClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorClear(evt);
            }
        });

        jBtnNumero7.setLabel("7");
        jBtnNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnNumero8.setLabel("8");
        jBtnNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnNumero9.setLabel("9");
        jBtnNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnOperacaoDiv.setLabel("/");
        jBtnOperacaoDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorOperacoes(evt);
            }
        });

        jBtnNumero4.setLabel("4");
        jBtnNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnNumero5.setLabel("5");
        jBtnNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnNumero6.setLabel("6");
        jBtnNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnOperacaoMul.setLabel("*");
        jBtnOperacaoMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorOperacoes(evt);
            }
        });

        jBtnNumero1.setLabel("1");
        jBtnNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnNumero2.setLabel("2");
        jBtnNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnNumero3.setLabel("3");
        jBtnNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnOperacaoSub.setText("-");
        jBtnOperacaoSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorOperacoes(evt);
            }
        });

        jBtnNumero0.setLabel("0");
        jBtnNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorNumeros(evt);
            }
        });

        jBtnPonto.setLabel(".");
        jBtnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorPonto(evt);
            }
        });

        jBtnOperacaoIgual.setLabel("=");
        jBtnOperacaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorIgual(evt);
            }
        });

        jBtnOperacaoAdi.setLabel("+");
        jBtnOperacaoAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratadorOperacoes(evt);
            }
        });

        jTextLog.setEditable(false);
        jTextLog.setFocusable(false);
        jScrollPane1.setViewportView(jTextLog);
        SimpleAttributeSet rightAlign = new SimpleAttributeSet();
        StyleConstants.setAlignment(rightAlign, StyleConstants.ALIGN_RIGHT);
        jTextLog.setParagraphAttributes(rightAlign, true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOperacaoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOperacaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOperacaoAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOperacaoMul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jBtnNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnOperacaoDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBntClear, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnNumero7, jBtnNumero8, jBtnNumero9, jBtnOperacaoDiv});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBntClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNumero7)
                            .addComponent(jBtnNumero8)
                            .addComponent(jBtnNumero9)
                            .addComponent(jBtnOperacaoDiv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNumero4)
                            .addComponent(jBtnNumero5)
                            .addComponent(jBtnNumero6)
                            .addComponent(jBtnOperacaoMul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNumero1)
                            .addComponent(jBtnNumero2)
                            .addComponent(jBtnNumero3)
                            .addComponent(jBtnOperacaoSub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNumero0)
                            .addComponent(jBtnPonto)
                            .addComponent(jBtnOperacaoIgual)
                            .addComponent(jBtnOperacaoAdi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tratadorNumeros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratadorNumeros
        // TODO add your handling code here:
        
        if (limpaTela) {
            jTextResultado.setText("");
            if ( this.operacao == null ) {
                jTextLog.setText(jTextLog.getText() + String.format("\n"));
            }
            limpaTela = false;
        }

        // Impede os zeros a esquerda
        if (jTextResultado.getText().equalsIgnoreCase("0")) {
            jTextResultado.setText("");
        }
        
        String texto = jTextResultado.getText() +
                       ((JButton)(evt.getSource())).getText();
        
        jTextResultado.setText(texto);
    }//GEN-LAST:event_tratadorNumeros

    private void tratadorPonto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratadorPonto
        // TODO add your handling code here:
        
        if (!limpaTela) {
            //Verifica se já existe um ponto e se não está vazio o campo
            if (!jTextResultado.getText().contains(".") &&
                !jTextResultado.getText().isEmpty()) {
                jTextResultado.setText(jTextResultado.getText() + ".");
            }
        }
    }//GEN-LAST:event_tratadorPonto

    private void tratadorClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratadorClear
        // TODO add your handling code here:
        this.calc = new Calculadora();
        jTextResultado.setText("");
        jTextLog.setText("");
        this.operacao = null;
        limpaTela = false; // Correção do bug de nova linha no log ao clicar em Clear.
    }//GEN-LAST:event_tratadorClear

    private void tratadorOperacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratadorOperacoes
        // TODO add your handling code here:
        
        try {
            String stringOp = ((JButton)(evt.getSource())).getText();
            Calculadora.Operacoes novaOperacao = Calculadora.obtemOperador(stringOp);
            
            // Já possuo o OP1 e a operação
            if (this.operacao != null) {
                if (this.limpaTela) {
                    // Só troco o operador
                    this.operacao = novaOperacao;
                } else {
                    double op2 = Float.parseFloat(jTextResultado.getText());
                    double resultado = calc.realizaOperacao(this.operacao, op2);
                    jTextLog.setText(jTextLog.getText() + String.format(Locale.US,"%.4f %s \n",op2,calc.obtemStringOperador(this.operacao)));
                    this.operacao = novaOperacao;
                    jTextResultado.setText(String.valueOf(resultado));
                }
            } 
            // É a primeira vez, então vou definir o OP1
            else {
                if (this.limpaTela) {
                    // Só troco o operador
                    this.operacao = novaOperacao;
                } else {
                    double op1 = Float.parseFloat(jTextResultado.getText());
                    this.calc.setOperando1(op1);
                    this.operacao = novaOperacao;
                    jTextLog.setText(jTextLog.getText() + String.format(Locale.US,"%.4f   \n",op1));
                }
                
            }
            
            // Se chegou aqui, tudo ok
            limpaTela = true;
            
        } catch (OperadorNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), NOME_DO_PROGRAMA, JOptionPane.ERROR_MESSAGE);
        } catch (Operando1NaoDefinidoException e) {
            JOptionPane.showMessageDialog(this, "Primeiro operando não definido", NOME_DO_PROGRAMA, JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, jTextResultado.getText() + " não é um número válido", NOME_DO_PROGRAMA, JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_tratadorOperacoes

    private void tratadorIgual(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratadorIgual
        // TODO add your handling code here:
        
        // Só realiza a operação se antes tiver sido definida uma operação
        try {
            if (this.operacao != null) {
                double valor = Float.parseFloat(this.jTextResultado.getText());
                double resultado = this.calc.realizaOperacao(this.operacao, valor);
                jTextLog.setText(jTextLog.getText() + String.format(Locale.US,"%.4f %s \n----------- \n%.4f   \n", valor,calc.obtemStringOperador(operacao),resultado));
                calc.SalvaResultadoDoIgual();
                this.operacao = null;
                jTextResultado.setText(String.valueOf(resultado));
                this.limpaTela = true;
            }
        } catch (Operando1NaoDefinidoException e) {
            JOptionPane.showMessageDialog(this, "Primeiro operando não definido", NOME_DO_PROGRAMA, JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, jTextResultado.getText() + " não é um número válido", NOME_DO_PROGRAMA, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_tratadorIgual

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        calc.SalvaOperacoes(); // Salva as operações no arquivo de log.
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        String Log = calc.getLog();
        
        if ( Log.equalsIgnoreCase("") ) { // Se o log estiver vazio,
            jTextLog.setText("");
        }
        else {
            jTextLog.setText(Log); // Coloca o log antigo no painel de log.

            jTextResultado.setText(String.valueOf(calc.getOp1())); // Coloca o ultimo número no campo de resultado da calculadora.
            limpaTela = true; // E seta limpaTela como true.
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBntClear;
    private javax.swing.JButton jBtnNumero0;
    private javax.swing.JButton jBtnNumero1;
    private javax.swing.JButton jBtnNumero2;
    private javax.swing.JButton jBtnNumero3;
    private javax.swing.JButton jBtnNumero4;
    private javax.swing.JButton jBtnNumero5;
    private javax.swing.JButton jBtnNumero6;
    private javax.swing.JButton jBtnNumero7;
    private javax.swing.JButton jBtnNumero8;
    private javax.swing.JButton jBtnNumero9;
    private javax.swing.JButton jBtnOperacaoAdi;
    private javax.swing.JButton jBtnOperacaoDiv;
    private javax.swing.JButton jBtnOperacaoIgual;
    private javax.swing.JButton jBtnOperacaoMul;
    private javax.swing.JButton jBtnOperacaoSub;
    private javax.swing.JButton jBtnPonto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextLog;
    private javax.swing.JTextField jTextResultado;
    // End of variables declaration//GEN-END:variables

    private Calculadora calc;
    private Calculadora.Operacoes operacao;
    private boolean limpaTela = false;
    
    private static final String NOME_DO_PROGRAMA = "Calculadora de Padaria";

}
